[package]
name = "control-server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.7", optional = true, features = ["ws"] }
masonry = { version = "0.4.0", optional = true }
masonry_winit = { version = "0.4.0", optional = true }
rand = "0.9.2"
serialport = { version = "4.8.1", optional = true }
thiserror = "2.0.17"
tokio = { version = "1", features = ["full", "sync"] }
winit = { version = "0.30.12", optional = true }
xilem = { version = "0.4.0", optional = true }
xilem_core = { version = "0.4.0", optional = true }

[features]
default = [ "physical-ui", "physical-board", "physical-manipulator" ]

# telnet = []
websocket = [ "dep:axum" ]
usb-serial = [ "dep:serialport" ]

gui = [ "dep:winit", "dep:xilem", "dep:xilem_core", "dep:masonry", "dep:masonry_winit" ]

physical-ui = [ "usb-serial" ]
emulated-ui = [ "gui" ]

physical-board = [ "websocket" ]
emulated-board = [ "gui" ]

physical-manipulator = [
    # "telnet",
    "usb-serial"
]
emulated-manipulator = [ "gui" ]
