[package]
name = "control-server"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.17"
tokio = { version = "1", features = ["full"] }

[features]
default = [ "physical-ui", "physical-board", "physical-manipulator" ]

telnet = []
websocket = []
usb-serial = []

gui = []

physical-ui = [ "usb-serial" ]
emulated-ui = [ "gui" ]

physical-board = [ "websocket" ]
emulated-board = [ "gui" ]

physical-manipulator = [ "telnet", "usb-serial" ]
emulated-manipulator = [ "gui" ]
