#ifndef MAIN_H
#define MAIN_H

#define RED_BUTTON 25
#define RED_BUTTON_LED 20

#define YELLOW_BUTTON 3
#define YELLOW_BUTTON_LED 18

#define GREEN_BUTTON 4
#define GREEN_BUTTON_LED 17

#define DISPENSE_STEPS 10000
#define DISPENSE_STEP_FREQUENCY 10

#define RELEASE_STEPS 3200
#define RELEASE_STEP_FREQUENCY 20

#define MOTOR_UART_TX 8
#define MOTOR_UART_RX 9

#define BOARD_RELEASE_MOTOR_ID 3
#define BOARD_RELEASE_MOTOR_EN 15
#define BOARD_RELEASE_MOTOR_STEP 14
#define BOARD_RELEASE_MOTOR_DIR 13

#define ROBOT_DISPENSER_MOTOR_ID 2
#define ROBOT_DISPENSER_MOTOR_EN 7
#define ROBOT_DISPENSER_MOTOR_STEP 6
#define ROBOT_DISPENSER_MOTOR_DIR 5

#define OPPONENT_DISPENSER_MOTOR_ID 0
#define OPPONENT_DISPENSER_MOTOR_EN 12
#define OPPONENT_DISPENSER_MOTOR_STEP 11
#define OPPONENT_DISPENSER_MOTOR_DIR 10

enum {
    MOTION_COMMAND_DISPENSE,
    MOTION_COMMAND_RELEASE
};

enum {
    SERIAL_COMMAND_DISPENSE_DONE,
    SERIAL_COMMAND_RELEASE_DONE
};

#endif
